### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by abnermora59** [rohitranaqh/ADB-FRP-Bypass#1]
How is this supposed to work if the android needs to have USB debugging on and the FRP doesn't allow one to activate it?

**Comment by quitehacker** [comment]
I had this issue with **_Asus Zenphone Max Pro M1_**.

Android Version : 11 (Not Sure . May be it was 10)
USB Debugging: Off

And I used this technique and **_it worked_**.

I know that ideally it should not have worked but it did.

Not Related: But this device's bootloader was unlocked. So, may be it gave some extra privileges or something, I don't know.
